dist: trusty

cache:
  directories:
    - .autoconf
    - $HOME/.m2

matrix:
  include:
    - name: "Test frontend"
      language: node_js
      node_js: 12
      before_script:
        - cd frontend
        - yarn install
      script: yarn test --passWithNoTests
    - name: "Test backend"
      os: osx
      language: java
      jdk: openjdk11
      before_script: cd backend
      script: mvn clean verify --fae

